---

- name: Add mappings to /etc/hosts
  # vagrant environment nodes
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { ip: 10.0.1.10, name: DevSecOps-Box.local }
    - { ip: 10.0.1.11, name: jenkins.local }
    - { ip: 10.0.1.15, name: gitlab.local }
    - { ip: 10.0.1.16, name: gitlab-runner.local }
    - { ip: 10.0.1.18, name: elk.local }
    - { ip: 10.0.1.20, name: vuln-management.local }
    - { ip: 10.0.1.22, name: prod.local }
  when: add_host_entries
