build:
	g++ main.cpp binary.cpp random.cpp bsc_canal.cpp trellis.cpp convolutional.cpp

test-encode:
	g++ test_encode.cpp binary.cpp random.cpp bsc_canal.cpp trellis.cpp convolutional.cpp

test-decode:
	g++ test_decode.cpp binary.cpp random.cpp bsc_canal.cpp trellis.cpp convolutional.cpp

estimate-times:
	g++ estimate_times.cpp binary.cpp random.cpp bsc_canal.cpp trellis.cpp convolutional.cpp
