build:
	g++ main.cpp random.cpp bsc_canal.cpp trellis.cpp encoder.cpp

test-encode:
	g++ test_encode.cpp random.cpp bsc_canal.cpp trellis.cpp encoder.cpp

test-decode:
	g++ test_decode.cpp random.cpp bsc_canal.cpp trellis.cpp encoder.cpp

estimate-times:
	g++ estimate_times.cpp random.cpp bsc_canal.cpp trellis.cpp encoder.cpp
