Vagrant.configure("2") do |config|
  config.vm.box = "inclusivedesign/windows10-eval"
  config.vm.hostname = "server"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2
  end
  config.vm.network :private_network, ip: "172.16.2.20"
  config.vm.provision "shell", path: "rdp.ps1"
end
