---

- name: Install gitlab runner
  hosts: all
  become: yes

  vars:
    gitlab_runner_registration_token: ''
    gitlab_runner_connect_enable: true

    # host entries won't work in docker
    # see https://stackoverflow.com/questions/28327458/how-to-add-my-containers-hostname-to-etc-hosts
    add_host_entries: true

    # Docker Community Edition
    docker_edition: 'ce'
    docker_package: "docker-{{ docker_edition }}"
    docker_package_state: present

    # Docker compose
    docker_install_compose: true
    docker_compose_version: "1.25.4"
    docker_compose_path: /usr/local/bin/docker-compose

    docker_apt_release_channel: stable
    docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

    # Packer
    packer_version: "1.5.5"
    packer_arch: "amd64"
    packer_bin_path: /usr/local/bin

    # Terraform
    terraform_version: "0.12.24"
    terraform_arch: "amd64"
    terraform_bin_path: /usr/local/bin

    # Install pip3 version
    pip_package: python3-pip
    pip_executable: pip3
    pip_install_packages:
      - name: virtualenv
      - name: ansible
        version: 2.9.6
      - name: ansible-lint
        version: 4.2.0
      - name: sslyze

  roles:
    - common
    - geerlingguy.docker
    - gitlab-runner
    - geerlingguy.pip
    - geerlingguy.packer
    - secfigo.terraform
    - python
    - cli-tools
  tags:
    - runner
