Vagrant.configure("2") do |config| 
  config.vbguest.auto_update = false 
  config.vm.provider :virtualbox do |vb| 
    vb.gui = false 
    vb.memory = 1024 
    vb.cpus = 1 
  end 
  config.vm.define "vm01" do |vm01| 
    vm01.vm.box = "generic/rhel8" 
    vm01.vm.hostname = "gandalf" 
    vm01.vm.network :private_network, ip: "172.28.128.202" 
    vm01.vm.provision "file", source: "files/change-gateway", destination:  "/tmp/change-gateway" 
    vm01.vm.provision "shell", inline: <<-'SHELL'
      cp /tmp/change-gateway /usr/local/bin/change-gateway
      sudo sh -c "echo nameserver 8.8.8.8 > /etc/resolv.conf"
      sudo /usr/local/bin/change-gateway 
      echo 'export http_proxy="http://172.28.128.200:8080/"' >> /etc/profile 
      echo 'export https_proxy="http://172.28.128.200:8080/"' >> /etc/profile 
    SHELL 
  end 
  config.vm.define "vm02" do |vm02| 
    vm02.vm.box = "generic/rhel8" 
    vm02.vm.hostname = "frodo" 
    vm02.vm.network :private_network, ip: "172.28.128.203"
  end 
end 

